### ISSUE TITLE
Recursive functions returns an error.

### ISSUE THREAD

**Issue by SkyzohKey** [Bat41/Spreadsheet#17]
![](https://0x0.st/YsL.png)

**Comment by Bat41** [comment]
Where is the recursive function? And what is the error you get in the console?

**Comment by SkyzohKey** [comment]
The error is the result of the formula, by recursive I mean that lines/colums multiplication, etc doesn't work with more than 2 :/

**Comment by Bat41** [comment]
Yes I saw the error in the table, but a more detailled one should have been logged into the console. Anyway, I'll just copy your formula and see by myself. 🙂
